function globalError() {
  const error = Error('Глобальная ошибка');
  error.name = 'GlobalError';
  throw error;
}

function localError() {
  const error = Error('Локальная ошибка');
  error.name = 'LocalError';
  throw error;
}

function testErrorScope(fn) {
  try {
    fn();
  } catch (error) {
    // Проверяем, является ли ошибка локальной
    if (error.name === 'LocalError') {
      console.log('Обнаружена локальная ошибка');
      console.error(error);
    } else {
      // Если ошибка не локальная, значит, она глобальная
      console.log('Обнаружена глобальная ошибка');
      console.error(error);
    }
  }
}

testErrorScope(localError);  // Выводит: Обнаружена локальная ошибка
testErrorScope(globalError);  // Выводит: Обнаружена глобальная ошибка